apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ubuntupipeline 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntupipeline 
    spec:
      containers:
        - name: ubuntupipeline 
          image: sgacreg.azurecr.io/ubuntupipeline
          ports:
          - containerPort: 80